blank_issues_enabled: true
contact_links:
  - name: Melody Support
    url: https://github.com/oyevipthoma88/Melody_music/issues
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://github.com/oyevipthoma88/Melody_music
    about: Documentation for getting started with bot.
