#!/usr/bin/env python3
"""
📱 Termux premium-emoji harvester for Melody.

WHAT IT DOES
------------
1. Logs in with YOUR Telegram *user* account (a bot can never read a channel's
   history or resolve premium emoji packs the way a user can).
2. Reads every message of a channel (default: https://t.me/OrderEmoji) and
   collects every `custom_emoji_id` found in message entities / caption
   entities — plus, for every id, the exact unicode glyph the artwork depicts.
3. VERIFIES each id against Telegram with `messages.GetCustomEmojiDocuments`.
   Ids Telegram cannot resolve are dropped, so the generated file only ever
   contains working ids.
4. Writes `utils/emoji_order_pack.py` (glyph -> [ids]) which
   `utils/emoji_map.py` already merges into the bot's glyph -> premium-id
   fallback chain. Every plain unicode glyph the bot prints therefore gets a
   premium animated counterpart.

USAGE IN TERMUX
---------------
    pkg update -y && pkg install -y python git
    pip install -U pyrofork tgcrypto
    git clone <your Melody repo> && cd Melody_music
    export API_ID=123456 API_HASH=xxxxxxxxxxxxxxxx
    python tools/termux_emoji_harvest.py --channel OrderEmoji

    # optional flags
    #   --channel  @username or -100xxxxxxxxxx (repeatable)
    #   --limit    how many messages to scan per channel (0 = all, default 0)
    #   --out      output path (default utils/emoji_order_pack.py)
    #   --print    just print glyph=id pairs, don't write the file

API_ID / API_HASH come from https://my.telegram.org -> API development tools.
The login session is stored as `melody_emoji.session` next to the script; keep
it private and never commit it.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from collections import OrderedDict
from pathlib import Path

try:
    from pyrogram import Client, raw
except ImportError:  # pragma: no cover
    sys.exit("Install pyrofork first:  pip install -U pyrofork tgcrypto")

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "utils" / "emoji_order_pack.py"
MAX_IDS_PER_REQUEST = 200  # Telegram's hard cap


def _strip_vs(glyph: str) -> str:
    """'▶️' and '▶' must key the same entry (the bot strips U+FE0F too)."""
    return (glyph or "").replace("\ufe0f", "")


async def collect_ids(app: Client, chat: str, limit: int) -> set[int]:
    """Every custom_emoji_id referenced anywhere in `chat`'s history."""
    found: set[int] = set()
    scanned = 0
    async for message in app.get_chat_history(chat, limit=limit or 0):
        scanned += 1
        for entities in (message.entities, message.caption_entities):
            for entity in entities or []:
                emoji_id = getattr(entity, "custom_emoji_id", None)
                if emoji_id:
                    found.add(int(emoji_id))
        # A forwarded/attached emoji sticker also carries the id directly.
        sticker = getattr(message, "sticker", None)
        if sticker is not None:
            emoji_id = getattr(sticker, "custom_emoji_id", None)
            if emoji_id:
                found.add(int(emoji_id))
        if scanned % 200 == 0:
            print(f"   … {scanned} messages, {len(found)} ids so far", flush=True)
    print(f"   ✔ {chat}: scanned {scanned} messages, found {len(found)} ids")
    return found


async def verify(app: Client, ids: list[int]) -> dict[int, str]:
    """Return {id: glyph} for ids Telegram really resolves (i.e. that work)."""
    working: dict[int, str] = {}
    for start in range(0, len(ids), MAX_IDS_PER_REQUEST):
        batch = ids[start:start + MAX_IDS_PER_REQUEST]
        try:
            documents = await app.invoke(
                raw.functions.messages.GetCustomEmojiDocuments(document_id=batch)
            )
        except Exception as exc:  # noqa: BLE001
            print(f"   ! batch {start}-{start + len(batch)} failed: {exc}")
            continue
        for document in documents or []:
            document_id = getattr(document, "id", None)
            if document_id is None:
                continue
            alt = None
            for attribute in getattr(document, "attributes", None) or []:
                if isinstance(attribute, raw.types.DocumentAttributeCustomEmoji):
                    alt = attribute.alt
                    break
            if alt:
                working[int(document_id)] = _strip_vs(alt)
        print(f"   … verified {min(start + MAX_IDS_PER_REQUEST, len(ids))}/{len(ids)}",
              flush=True)
    return working


HEADER = '''"""
🎨 Premium (animated) custom-emoji ids harvested from the owner's reference
channel(s): {sources}.

AUTO-GENERATED by `tools/termux_emoji_harvest.py` — do not hand-edit.
Every id below was verified against Telegram with
messages.GetCustomEmojiDocuments at generation time, and each is paired with
the exact unicode glyph its artwork depicts (read from the same document), so
the glyph -> id pairing cannot drift the way a hand-written map does.

`utils.emoji_map` merges this into the glyph -> id fallback chain, so any plain
unicode glyph used anywhere in the bot renders as a premium emoji.

Generated: {count} working ids across {glyphs} glyphs.
"""

ORDER_EMOJI_MAP: dict[str, list[str]] = {{
'''

FOOTER = '''}}

ORDER_EMOJI_ID_POOL: tuple = tuple(
    eid for ids in ORDER_EMOJI_MAP.values() for eid in ids
)
'''


def render(mapping: dict[str, list[str]], sources: str) -> str:
    ordered = OrderedDict(sorted(mapping.items(), key=lambda kv: kv[0]))
    body = "".join(
        "    {!r}: [{}],\n".format(glyph, ", ".join(f'"{i}"' for i in ids))
        for glyph, ids in ordered.items()
    )
    total = sum(len(v) for v in ordered.values())
    return (
        HEADER.format(sources=sources, count=total, glyphs=len(ordered))
        + body
        + FOOTER.format()
    )


async def main() -> int:
    parser = argparse.ArgumentParser(description="Harvest premium emoji ids for Melody")
    parser.add_argument("--channel", action="append", default=None,
                        help="channel username or id (repeatable). Default: OrderEmoji")
    parser.add_argument("--limit", type=int, default=0,
                        help="messages to scan per channel (0 = all)")
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--print", dest="dry", action="store_true",
                        help="print pairs instead of writing the file")
    args = parser.parse_args()

    channels = args.channel or ["OrderEmoji"]
    api_id = os.environ.get("API_ID")
    api_hash = os.environ.get("API_HASH")
    if not api_id or not api_hash:
        return int(bool(sys.stderr.write(
            "Set API_ID and API_HASH first:\n"
            "  export API_ID=123456 API_HASH=xxxxxxxx\n"
            "(get them from https://my.telegram.org)\n"
        ))) or 1

    session_dir = Path(__file__).resolve().parent
    app = Client("melody_emoji", api_id=int(api_id), api_hash=api_hash,
                 workdir=str(session_dir))

    async with app:
        me = await app.get_me()
        print(f"👤 Logged in as {me.first_name} (@{me.username or me.id})")

        all_ids: set[int] = set()
        for channel in channels:
            print(f"📥 Scanning {channel} …")
            try:
                all_ids |= await collect_ids(app, channel, args.limit)
            except Exception as exc:  # noqa: BLE001
                print(f"   ! could not read {channel}: {exc}")

        if not all_ids:
            print("❌ No custom emoji ids found. Join the channel and retry.")
            return 1

        print(f"🔎 Verifying {len(all_ids)} ids against Telegram …")
        working = await verify(app, sorted(all_ids))
        broken = len(all_ids) - len(working)
        print(f"✅ {len(working)} ids working, ❌ {broken} dropped (dead/unresolvable)")

    mapping: dict[str, list[str]] = {}
    for emoji_id, glyph in sorted(working.items(), key=lambda kv: kv[1]):
        mapping.setdefault(glyph, []).append(str(emoji_id))

    if args.dry:
        for glyph, ids in sorted(mapping.items()):
            print(glyph, "->", ", ".join(ids))
        return 0

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(mapping, ", ".join(channels)), encoding="utf-8")
    print(f"💾 Wrote {out} — {len(mapping)} glyphs, "
          f"{sum(len(v) for v in mapping.values())} ids")
    print("👉 Commit it and redeploy:  git add utils/emoji_order_pack.py && "
          "git commit -m 'emoji: refresh premium ids' && git push")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
